### ISSUE TITLE
Rename light/dark functions as they return boolean value

### ISSUE THREAD

**Issue by felixsanz** [Qix-/color#101]
This functions:

```javascript
color.light();  // true
color.dark();   // false
```

They return a boolean, so the API should be `color.isLight()` and `color.isDark()`. :(

Being just `light()` it seems like it returns a light version of the color, or something like that.

It is too late to push it into 1.x? Maybe add this methods and move `light()` and `dark()` as an alias?

**Comment by felixsanz** [comment]
```javascript
	isDark: function () {
		// YIQ equation from http://24ways.org/2010/calculating-color-contrast
		var rgb = this.rgb().color;
		var yiq = (rgb[0] * 299 + rgb[1] * 587 + rgb[2] * 114) / 1000;
		return yiq < 128;
	},

	isLight: function () {
		return !this.isDark();
	},

	dark: function () {
		return isDark();
	},

	light: function () {
		return !this.isDark();
	},
```

**Comment by felixsanz** [comment]
I've created PR #102

**Comment by Qix-** [comment]
So I agree with the _spirit_ of these comments, though the solution I feel is just another bandaid patch (especially the PR).

There's this creeping problem of the library outgrowing its flat API style now that many different color models are included.

There needs to be some more thought put into the overall API and how we can silo things out a bit more to include the vast amounts of color operations that can occur between all of the different color models. This also includes the fact I want to support color space manipulation in the future, as well as support color schemes (e.g. specify multiple colors and perform batch operations on them).

The API is quickly growing a bit out of control, so the light/dark descriptiveness problems will be resolved when the solution to the above mentioned problem is found.
