### ISSUE TITLE
v1.0.3 rgbaArray no alternative method?

### ISSUE THREAD

**Issue by septs** [Qix-/color#104]
I would like to be able to change the `array()` signature into `array(rgba = false)`

see https://github.com/Qix-/color/blob/v0.7.3/color.js#L92-L95
see https://github.com/Qix-/color/blob/f1f880d072601625fe4d87a6fecec2b7ee99c1ce/index.js#L141-L143

**Comment by Qix-** [comment]
I'm not entirely sure what you're after here. Could you explain a bit more?

**Comment by septs** [comment]
v1.0.3 remove rgbaArray feature, this feature v0.7.3 include

**Comment by Qix-** [comment]
It's just `.rgb().array()` now.
