### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by JestDotty** [Qix-/color#111]
Apparently used to be versions of it? But in old readme/gh pages?

normally npm modules have a folder called dist with minified browser versions of a lib

**Comment by Qix-** [comment]
Anymore I figured the trend was to use Webpack, right?

**Comment by Seudein** [comment]
... Except I don't use it. This adds extra steps, extra dependencies, and
makes it non modular/standalone in design.

I thought the whole point of the npm ecosystem was to abstract away the
complex and be easy to use. This seems like an anti pattern.

I looked at d3 colours and was surprised to find the same issue. However
then I found an npm library that supports both.

I was a little scared; I actually quite love node.js and I was of the
opinion the people complaining about how ridiculous the ecosystem is just
didn't understand how to use it... I hope we don't predominantly become
like that =S

**Comment by Qix-** [comment]
cc // @sindresorhus thoughts? Web packaging with NPM isn't my forte - I've never distributed minified versions of my code on NPM.

**Comment by sindresorhus** [comment]
> I thought the whole point of the npm ecosystem was to abstract away the
complex and be easy to use.

It is and it does, but for Node.js. The browser world is a whole other nightmare.

> I was a little scared; I actually quite love node.js and I was of the
opinion the people complaining about how ridiculous the ecosystem is just
didn't understand how to use it...

They clearly don't, but this issue isn't about the Node.js ecosystem, but rather using npm packages in the browser. Not sure why you assume things will just work in the browser. Maybe that will be a good assumption when we all use ES2015 modules everywhere, but that's not the reality today.

---

It's up to you to handle the browser. The code is all there, but it's up to you to decide how to package it. You could use Webpack or you could use something else. See: https://github.com/sindresorhus/ama/issues/446
