### ISSUE TITLE
not compatible with latest version of color-convert

### ISSUE THREAD

**Issue by cenkentimist** [Qix-/color#112]
the following code in color now fails due to the addition of new things in convert.
```
    var hashedModelKeys = {};
    Object.keys(convert).forEach(function (model) {
        hashedModelKeys[_slice.call(convert[model].labels).sort().join('')] = model;
    });
```

**Comment by cenkentimist** [comment]
Woops this was caused by a version conflict. I was pulling in an old version.

**Comment by umaxfun** [comment]
How did you solve the problem? It's repeated in my case.

`➜  tentacle git:(master) ✗ yarn add color                                       git:(master|✚5…
yarn add v0.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning Unmet peer dependency "uglify-js@^2.8.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
├─ color-convert@1.9.0
├─ color-string@1.5.2
├─ color@1.0.3
├─ is-arrayish@0.3.1
└─ simple-swizzle@0.2.2
✨  Done in 7.88s.`

`Uncaught TypeError: Array.prototype.slice called on null or undefined
    at slice (<anonymous>)
    at index.js:21
    at Array.forEach (<anonymous>)
    at Object.../node_modules/color/index.js (index.js:20)`

**Comment by cenkentimist** [comment]
I made the version of color convert explicit by adding "color-convert": "^1.9.0" to the package.json for the project.

**Comment by Qix-** [comment]
Hi - please remove your lock file and try again. You have a version mismatch, or it's a bug in your package manager (most likely the former).

There's no way this error would occur if you're using the latest version of `color`.
