### ISSUE TITLE
Colors not showing up for gradle output

### ISSUE THREAD

**Issue by kuhu19** [Qix-/color#113]
I am using this package to color my node outputs. It works great when I run it through node but colors disappear when I call the node script from my gradle task. Only the colors set using this package are disappearing, other packages retain their colors. So, I was thinking that the problem cannot be with gradle settings.

My Node function -
`function runCommand(command) {
  Promise.coroutine(function *() {
    var response = yield cmd.run(command);
    if(response.success) {
        console.log("Command was successful".green);
    } else {
        console.log("Commad Failed.".red);
    }
  })();
}`

`runCommand("dir");`

Calling function from gradle-
`task runCmd(type:NodeTask,dependsOn: 'npmInstall'){
    script = file('runCommand.js')
}`

**Comment by Qix-** [comment]
This is the wrong repo. You're using [`colors`](https://github.com/Marak/colors.js), not `color`.

Also, this is expected behavior. See if `colors` has some equivalent of `FORCE_COLOR`.

**Comment by kuhu19** [comment]
Thanks for your thoughts. I would check it out.
