### ISSUE TITLE
feature suggestion: linear interpolation

### ISSUE THREAD

**Issue by jslz** [Qix-/color#115]
(If I find the time I'll make a PR but dunno if/when that would ever really happen...)
Color.lerp(startColor,endColor,parameter)
where parameter gets internally clipped to 0...1 inclusive.
var c1 = Color.rgb(0,0,0);
var c2 = Color.rgb(0,128,255);
var c3 = Color.lerp(c1,c2,1); // rgb(0,128,255)
var c4 = Color.lerp(c2,c1,1); // rgb(0,0,0)
var c5 = Color.lerp(c1,c2,0.5); // rgb(0,64,127.5) or something like that.

**Comment by Qix-** [comment]
```javascript
c1.mix(c2, 0.2);
```

Second parameter defaults to `0.5` if not specified.

💃

**Comment by jslz** [comment]
oh, thanks! I did see mix but didn't grok that it was == lerp. I will use that.

**Comment by Qix-** [comment]
@jslz Yep! I agree _lerp_ is a more common term in graphics programming but you don't see it much outside the shader realm.
