### ISSUE TITLE
Color conversion returns only "RGB"

### ISSUE THREAD

**Issue by rafa-acioly** [Qix-/color#121]
I'm trying to do the conversion as follows:
```js
let color = Color(term); // term is #7743CE
const colors = {
  hsl: color.hsl().string(),
  rgb: color.rgb().string(),
  cmyk: color.cmyk().string(),
  hsv: color.hsv().string(),
  ansi256: color.ansi256().string(),
}
```

But when I inspect the variable it is structured as follows.

```js
ansi256:"rgb(102, 51, 204)"
cmyk:"rgb(119, 67, 206)"
hsl:"hsl(262.4, 58.6%, 53.5%)"
hsv:"rgb(119, 67, 206)"
rgb:"rgb(119, 67, 206)"
```

**Comment by Qix-** [comment]
CMYK, HSV, and Ansi256 don't have CSS string representations. What is your expected output?

**Comment by rafa-acioly** [comment]
The excepted output;

HSV: `hsv(262°, 67%, 81%)`
HSL: `hsl(262°, 59%, 54%)`
CMYK: `cmyk(42%, 67%, 0%, 19%)`

You can see the result using google, just type the color in hex.

![](http://www.putimg.net/pictures/1501791220.png)

**Comment by Qix-** [comment]
You see `rgb()` and `hsl()` since those are valid CSS(3) color representations.

There is no such thing as `cmyk()` or `hsv()` in CSS3.
