### ISSUE TITLE
programmatic equivalents of string constructors e.g. rgba

### ISSUE THREAD

**Issue by jslz** [Qix-/color#122]
There's Color.rgb(255,255,255,0.5) which doesn't use strings, but I guess there's no Color.rgba()? Should there be non-string-parsing versions of things?

**Comment by Qix-** [comment]
I'm not sure what you mean. The main constructor accepts strings:

```javascript
new Color('rgba(10, 150, 45, 0.2)')
```

And `Color.rgb(r, g, b, a=1.0)` is just a static factory method.

What are you trying to achieve?

**Comment by jslz** [comment]
hi, thanks, sorry for being unclear -- it confused me that Color.rgba() is not a function at all, but Color.rgb() is. Doing Color.rgb().alpha() is weird to my eyes. Dunno if that explains it any better. Basically if there's a constructor via strings, I'd expect there to be an equivalent pure-code non-string-parsing based version. I'm led to expect this since Color.rgb() exists, I think.

**Comment by Qix-** [comment]
The following should do what you're intending:

```javascript
new Color({r: 10, g: 150, b: 45, alpha: 0.2});

// or

new Color([10, 150, 45, 0.2], 'rgb');
```

**Comment by jslz** [comment]
thanks, cool.

**Comment by Qix-** [comment]
Going to keep this open so I can modify the static constructors :) You're right in that they should accept alpha.

**Comment by Qix-** [comment]
The constructors accept alpha, so perhaps this is just an issue with docs - in which case, I'm going to close in favor of #181. Please correct me if I'm mistaken somehow.
