### ISSUE TITLE
Empty Color constructor returns black value

### ISSUE THREAD

**Issue by samjbmason** [Qix-/color#124]
When calling Color with `Color('')` it returns a black value. It feels like this should probably throw an error of an unrecognised string. Is this a known issue?

**Comment by Qix-** [comment]
No, it's pretty common that black is the default. `new Color()` is the same thing - black.

**Comment by Qix-** [comment]
Came back and re-read this. I agree with you, but I think this is a problem with `color-string`, not `color`. Will file as a bug for now. Thanks for letting me know :)

**Comment by narrator0** [comment]
@Qix- do I would like to submit a pr for this. Do you still need a pr for this?

**Comment by Qix-** [comment]
Sure, absolutely. Throw if color-string returns null.
