### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by matej-marcisovsky** [Qix-/color#132]
What is the difference between 1.0.3 and 2.0.0? There is no changelog.

**Comment by yashcr07** [comment]
It seems like the `mix` function got inverted somewhere between pre-1.x and 2.0.

**Comment by kumarharsh** [comment]
Yup: https://github.com/Qix-/color/pull/117

**Comment by matej-marcisovsky** [comment]
Thanks, but I would like to see change logs of future versions at least here in releases. @Qix- What do you think?

**Comment by Qix-** [comment]
:-1: on changelogs. I'll start putting things in the releases tab on Github.

**Comment by kumarharsh** [comment]
You can use something like `semantic-release` +`conventional-changelog`  to automatically generate a changelog for you and put it in the releases.

Also, reading migration steps in each individual PR is not exactly a dev-friendly or scalable approach.

**Comment by jaapz** [comment]
Why 👎 on changelogs? Just makes it artificially harder for someone to figure out what changed between versions. 

For anyone coming here for the same reason as me: the only thing changing between v2.0.1 and v3.0.0 was that the `dark` and `light` methods were renamed to `isDark` and `isLight`.

**Comment by Qix-** [comment]
Sorry, changelogs are a dead breed of documentation.
