### ISSUE TITLE
lighten a moderate color leads to white

### ISSUE THREAD

**Issue by ppaul** [Qix-/color#135]
I'm using this color rgb(252,103,102) in my project for some dropdowns selected values; the hover value should be the same, but lightened with 0.73. We have other similar colors in the project. Some work, but this gets a white lightened value, due to 100% max allowed: hsl(0.39999999999997726, 96.2%, 100%). If instead of 100% it was 95 or 96, the colour would be OK.. The point is I don't think lighter should be white, even if somehow mathematically gets that result.

**Comment by Qix-** [comment]
@ppaul While I agree this isn't ideal for your use-case, this module is intended to be mathematically correct. Lighten works with the luminosity channel of the HSL color model and increases it by a ratio.

I suggest experimenting with `.mix()` and passing different shades of grey as the parameter for the effect you're looking for. :)
