### ISSUE TITLE
RGBA breaks light/dark/luminosity

### ISSUE THREAD

**Issue by afrankel-sfdo** [Qix-/color#136]
Supplying a color via RGBA breaks the calculations for light/dark/luminosity. They don't seem to take into account the alpha transparency when calculating. 

```
color('rgba(0, 0, 0, 1)').luminosity() = 0
color('rgba(0, 0, 0, 0.87)').luminosity() = 0
color('rgba(0, 0, 0, 0.54)').luminosity() = 0 
color('rgba(0, 0, 0, 0.12)').luminosity() = 0
```

These all equal 0. 

I would expect the lower opacity to result in a higher luminosity given how those colors actually render.

**Comment by Qix-** [comment]
Alpha is just a value used to blend two colors. Black with any alpha value will always have a luminosity of 0 (keep in mind that luminosity is a channel within the HSL model).

This is intended functionality.

What are you trying to accomplish?

**Comment by afrankel-sfdo** [comment]
What I was trying to figure out is the effective rendered color luminosity when backed by a white background. Granted if those were backed by a different color, the results would be varied, so there is no generalized way of determining that just from the rgba supplied values. Ended up converting using a function which takes the rgba value plus an rgb background color, and coverts to a combined rgb value (basically how it "looks" to your eye).

**Comment by Qix-** [comment]
You could also `.mix()` based on the `.alpha()` value, too. But no, alpha is there as a convenience - IIRC none of the manipulation methods do anything with it. There's no magical default background color or anything, they all work with their non-alpha channels for the respective color models.
