### ISSUE TITLE
Including color in a typescript file

### ISSUE THREAD

**Issue by dingo-d** [Qix-/color#139]
I am trying to use `color` package in my `.ts` file, but no matter if I use 

```ts
import color from 'color';
```

or

```ts
import * as color from 'color';
```

I get 

> Could not find a declaration file for module 'color'. .../node_modules/color/index.js' implicitly has an 'any' type.
> Try `npm install @types/color` if it exists or add a new declaration (.d.ts) file containing `declare module 'color';

So is the only way to use it to declare color module in the `.d.ts` file?

**Comment by dingo-d** [comment]
Ok, found out about this: https://www.npmjs.com/package/@types/color

`import * as color from 'color';` does the trick

**Comment by vjsingh** [comment]
FYI for anyone who finds this, I got this to work by installing @types/color, and doing:

```
import Color from 'color';
```

**Comment by nathan-invision** [comment]
You'll also need to add `"esModuleInterop": true` to your .tsconfig compiler options.

**Comment by LifeIsStrange** [comment]
@vjsingh I get the following error Default export is not declared in imported module

**Comment by Qix-** [comment]
@types/color should _not_ be packaging `color` with it...

**Comment by LifeIsStrange** [comment]
@Qix- yeah in an ideal world @types/color would be always up to date with color hence it could be allowed to _not_ package `color` 

But "sadly" it is not up to date (3.0.1 vs 3.1.2) hence if it had been decoupled I couldn't have got it to works (unless hardcoding color in package.json to 3.0.1 too, which would be an inferior ergonomics for new library users.

**Comment by Qix-** [comment]
> unless hardcoding color in package.json to 3.0.1 too, which would be an inferior ergonomics for new library users

This is what you'd need to do, though. Or open a PR with DefinitelyTyped to update the typings.

I don't use Typescript nor do I maintain the DT definitions for any of my libraries.
