### ISSUE TITLE
check if string is color

### ISSUE THREAD

**Issue by KostblLb** [Qix-/color#140]
hi! is there some method for checking if a string is color? like Color.isColor('notColor') ? if there isn't, could you make one please? :)

**Comment by Qix-** [comment]
@KostblLb Check out `color-string` :)

**Comment by KostblLb** [comment]
another day, another dependency...

**Comment by Qix-** [comment]
@KostblLb Welcome to modular programming. `color-string` has no dependencies, and `color` already relies upon `color-string`.
