### ISSUE TITLE
Avoid overwriting Color.prototype with a plain object

### ISSUE THREAD

**Issue by btpoe** [Qix-/color#143]
Some background: I'm using [styled-components](https://www.styled-components.com) and I would love to use `color` to manage the colors in the project.

The issue is `styled-components` uses [is-plain-object](https://www.npmjs.com/package/is-plain-object) under the hood to determine if it should attempt to stringify the plain object itself. If it isn't a plain object, it will call `obj.toString()` (that's what I want it to do).

The problem is `is-plain-object` checks the prototype to determine if a variable is a plain object or not and `color` overwrites the prototype with a plain object.

My suggestion is to either use object assign:

```javascript
Object.assign(Color.prototype, {
 ...
});
```

or assign each method separately:

```javascript
var proto = Color.prototype;

proto.toString = function () { ... };

proto.hex = function () { ... };
```

**Comment by Qix-** [comment]
Why? This is very clearly a bug in whatever traverses objects as it's *very common* to overwrite `.prototype` with a plain object. Has been for decades.

**Comment by th0th** [comment]
Hey @btpoe, did you find a workaround for this one?

**Comment by th0th** [comment]
Thanks for the suggestion @Qix-, I just wanted to see if he found an easier solution :)

**Comment by Qix-** [comment]
Easier or not, it's not correct. Don't cut corners. It doesn't help anyone.

**Comment by btpoe** [comment]
```
import Color from 'color';
Color.prototype.constructor = Color;
```
