### ISSUE TITLE
Create a new hexa color mixing hexa and opacity

### ISSUE THREAD

**Issue by mdiegoku** [Qix-/color#145]
Hello! First, thanks for the amazing library, I've been using it and its been super helpful.

What I want to achieve, is that given an hexa color, and an opacity, I want to return a new hexa color based on that.

For example, I receive `#000000` as a parameter, and I want to make it lighter by 90%, which translates to the color `#e6e6e6`.

The problem is by doing this: `Color('#000000').alpha(0.1).string()`, I get `rgba(0, 0, 0, 0.1)` 

I would like to transform that to a new `hex` color, is that possible? 

The reason I want this, is because if I apply an `rgba` color to a fixed header, it will show transparency, and I don't want that to happen. 

Thanks in advance

**Comment by illuminist** [comment]
I'd do `Color('#000000').mix(Color('white'), 0.9).string()` which give back `rgb(230, 230, 230)` or.

**Comment by Qix-** [comment]
I'm not sure what you're asking for. @illuminist is correct, you need to mix.

Transparency doesn't imply white, and because of that, `color` doesn't _do_ much of anything with alpha - it just keeps track of it for you.

You're looking to mix into white :)
