### ISSUE TITLE
'Cannot read property 'length' of null' when attempting `new Color(null)`

### ISSUE THREAD

**Issue by jstevans** [Qix-/color#151]
Prior to `color@3.1.0`, it was possible to call `new Color(null)` and get back a `Color` corresponding to `rgb(0,0,0)`. Now, this throws an exception `"Cannot read property 'length' of null"`.

**Comment by Qix-** [comment]
This was a bug we just fixed, you shouldn't be passing `null`. Why not pass `0`, or even better `0x000000` to be explicit about wanting black? `new Color(null)` doesn't tell other people reading your code which color you're after.

**Comment by jstevans** [comment]
Agreed in principle, and I can't speak to the motivation; only that this was an existing behavior, and seems inline with accepting `new Color(undefined)`.

**Comment by Qix-** [comment]
Existing behavior that was a bug and undocumented. Passing undefined is not a valid argument; you shouldn't be using undefined directly in code aside from testing for it.
