### ISSUE TITLE
Contribution proposal 😇

### ISSUE THREAD

**Issue by robertrossmann** [Qix-/color#159]
Hi!

I would like to contribute to this project as I am using `color` on a side project of mine. I have the following changes in mind - could you please take a look at them and let me know if you'd be interested in a PR implementing these changes before I actually commit time & effort to them? 🙏

- Upgrade `color-convert` to v2
- Drop support for EOL-ed Node.js versions (semver-major ⚠️)
- Upgrade `xo` to `0.24` and update codez to match new rulez 🕵
- Add _package-lock.json_ so that every contributor gets to work against the same set of deps 😍 
- *Implement `.ahex()` & `.hexa()`, include tests (similar to #158)

**Comment by Qix-** [comment]
- Sure, upgrade away.
- Sure, drop EOL - needs to be its own PR
- Sure, upgrade XO and fix any resulting issues - needs to be its own PR.
- No, please do not add lockfiles. They are conceptually flawed, designed and implemented carelessly, and only cause headache.
- Is there a problem with #158? I just haven't gotten around to OSS lately.

Also, please way less emojis...
