### ISSUE TITLE
Hosted API

### ISSUE THREAD

**Issue by chrisvxd** [Qix-/color#169]
Hey @Qix- 👋 Thanks for the awesome library.

I'm looking to convert open source libs into SaaS APIs as part of my work with [saasify.sh](https://saasify.sh) and thought color would be a great fit.

Here's a working demo of what I was thinking, generated from [this source](https://github.com/saasify-sh/saasify/tree/master/examples/typescript/color):

```bash
curl -X POST \
  'https://api.saasify.sh/1/call/dev/color@a9f6c384/convert' \
  -H 'content-type: application/json' \
  -d '{
  "input": "#f08a5d",
  "outputType": "hsv"
}'
```

There's also a demo for a [standalone SaaS site](https://color.saasify.sh) generated from the same source.

We'd like to offer a rate-limited API and reserve most of the profits for you. As an example, we've also worked on converting sindresorhus' [imagemin](http://imagemin.saasify.sh/) and minimaxir's [stylecloud](http://wordcloud.saasify.sh/) to APIs.

Looking forward to hearing your thoughts! Would also be happy to jump on a quick call to discuss.

**Comment by Qix-** [comment]
Not interested.
