### ISSUE TITLE
@types/color: error TS2716: Type parameter 'T' has a circular default. 

### ISSUE THREAD

**Issue by curiouscod3** [Qix-/color#176]
> node_modules/@types/color/index.d.ts(13,40): error TS2716: Type parameter 'T' has a circular default.

In Angular project,( regardless of framework type)

To fix this, I had to change from this :
`type ColorParam = Color | string | ArrayLike<number> | number | { [key: string]: any };`

to this 
`type ColorParam = string | ArrayLike<number> | number | { [key: string]: any };`

Any better idea?

**Comment by Qix-** [comment]
Please open an issue with definitelytyped. I do not maintain the typings.
