### ISSUE TITLE
Unable to parse color from string: 00ff00

### ISSUE THREAD

**Issue by weaver** [Qix-/color#180]
Hello, I came across this error today. It looks like `#00ff00` works but `00ff00` does not (missing `#` prefix. I'm doing this as a workaround. Any chance of supporting hex strings with an optional octothorp?

```const parseColor = (input: string) => {
  try {
    return Color(input)
  } catch(originalError) {
    try {
      // Is this a 'Unable to parse color from string' error?      
      return Color('#' + input);
    } catch(_) {
      throw originalError;
    }
  }
}```

**Comment by Qix-** [comment]
> Any chance of supporting hex strings with an optional octothorp

Nope. Please have the `#` prefix. `color` uses `color-string` under the hood, which expects a proper CSS color string. 

Alterantively, pass a number instead of a string.

```javascript
console.log(new Color(0x00FF00).hex()); // "#00FF00"
```
