### ISSUE TITLE
Logic behind converting between models

### ISSUE THREAD

**Issue by isa3bel** [Qix-/color#183]
do you think you could explain to me the logic of how you convert values from one model to another? The code seems to abstract some of that logic, and it's a bit hard to tell what's going on. do you use the formulas from this website? --> https://www.easyrgb.com/en/math.php. More specifically, **I would like to know how you go from RGB to LAB and vice versa.**

**Comment by Qix-** [comment]
Hi @isa3bel - this package has two sister packages, [`color-convert`](https://github.com/qix-/color-convert) and [`color-string`](https://github.com/qix-/color-string).

`color-convert` is the package that contains all of the color conversion logic :) This package (`color`) is just a more human-friendly wrapper around those packages.

Hope that helps! :)

**Comment by isa3bel** [comment]
Thank you @Qix- for the fast response! It seems like that other package is using a formula from https://www.easyrgb.com/en/math.php. Is this the website that you used to form the formulas in color-convert? Thanks again

**Comment by Qix-** [comment]
I really couldn't say, that package is pretty old and has been updated quite a lot.

There's a fair chance it's the other way around - they might have gotten their formulas from that package. It's not uncommon for that to be the case :)

The formulas for these models have been known for a while, however. I would imagine they're quite the same.
