### ISSUE TITLE
Please provide esm version

### ISSUE THREAD

**Issue by gliheng** [Qix-/color#184]
New build tool prefer esm module only. And this lib cannot be used in new build tools eg. vite. It's usefull to publish esm version and move forward.

**Comment by Qix-** [comment]
Not going to happen until it becomes the standard, sorry. I don't cater to individual build tools.

**Comment by JeanMeche** [comment]
Then maybe reopen the ticket for the moment ? 

Correct me if I'm wrong, but you haven't released an esm yet ?

**Comment by michaelfaith** [comment]
@Qix- is this still planned for release?  Would it be prudent to re-open this issue, now that you've agreed to take the request?
