### ISSUE TITLE
hex with rgba

### ISSUE THREAD

**Issue by DrDr3ck** [Qix-/color#188]
Hi,

if I got a rgb color on which I add an alpha, the hex function will only return the rgb transformation and not the rgba transformation. Is it expected ? Should we have a hexa() function that will return the rgba transformation ?

example:
const color = Color("#72FFFF");
color.alpha(0.5);
console.log(color.hex());

=> #72FFFF

**Comment by Qix-** [comment]
Please search the issues before opening a new issue.

Duplicate of #125.
