### ISSUE TITLE
Error in test

### ISSUE THREAD

**Issue by Belingheri** [Qix-/color#192]
Hi i just clone the project before do changes i try to run `npm test` but i have this error.
What can i do?
![image](https://user-images.githubusercontent.com/33315640/109067988-8e348500-76ef-11eb-86d2-8aed1a450cce.png)

**Comment by Qix-** [comment]
Doesn't happen to me, you must have upgraded `xo`. I haven't freshened up the test dependencies lately, so the source won't adhere to newer XO (eslint) rules.

If I'm wrong and you're pulling from master, installing and immediately running tests, then please let me know and I can help investigate. Please also show all of the exact commands you ran to clone and run tests, please.
