### ISSUE TITLE
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by lynx-falyoun** [Qix-/color#214]
I am trying to use **color** package in Angular application but it throws the following error

> ERROR in ./node_modules/color/index.js 257:26
Module parse failed: Identifier directly after number (257:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|               for (const [i, element] of rgb.entries()) {
|                       const chan = element / 255;
>                       lum[i] = (chan <= 0.039_28) ? chan / 12.92 : ((chan + 0.055) / 1.055) ** 2.4;
|               }
|

**Comment by Qix-** [comment]
Please search existing issues next time.

**Comment by Qix-** [comment]
Copying and pasting the error message directly into the search bar would have shown them at least a few other issues.

https://github.com/Qix-/color/issues?q=%22Identifier+directly+after+number%22

It doesn't take much effort not to waste others' time.
