### ISSUE TITLE
Just a small fix to make compatible with Node 10

### ISSUE THREAD

**Issue by BrOrlandi** [Qix-/color#220]
On index.js line 257 there's this code:
```js
lum[i] = (chan <= 0.039_28) ? chan / 12.92 : ((chan + 0.055) / 1.055) ** 2.4;
```

Can you just remove the `_` from the number `0.039_28`? This will make the lib compatible with Node 10 and 12.
I currently updated another lib that depends on this one, but it breaks on Node 10 due to this line.
I'm not able to update the node version because it would require more code changes due to other dependencies. And I think that removing this character would be enough to make the lib compatible again.

It's possible?

**Comment by BrOrlandi** [comment]
I read some issues about it, and I am ok to make a fork on it if you just don't agree with the change.

**Comment by Qix-** [comment]
Yep, you can fork it.
