### ISSUE TITLE
Error "No identifiers allowed directly after numeric literal" in some environments

### ISSUE THREAD

**Issue by pcprinz** [Qix-/color#223]
I recently created a npm package that uses color version 4.0.1. More specifically, I am using the `Color(string)`  constructor and the ` red()`, `green()`  and ` blue()` methods.

That's all: 
```typescript      
const rgb = Color(color);
...
Math.round(rgb.red()),
Math.round(rgb.green()),
Math.round(rgb.blue())
```

If I use my package in a pure Javascript environment, or in a compiled Typescript app, then I have no problems. However, when I include my package in a React Native project, I get this error:

```
No identifiers allowed directly after numeric literal
No identifiers allowed directly after numeric literal
no stack
no stack
```

It took me hours to find that downgrading Color back to version <4 will fix this problem. So far, however, I have not been able to find out what exactly is causing the error, since, as you can see, no stack exists either. The following issue brought me to solving the problem and the connection with *Color*:
https://github.com/polkadot-js/ui/issues/516

**Comment by Qix-** [comment]
Please search the issues next time. This is brought up almost daily at this point. You need to bug the React folks to support modern JavaScript.

> It took me hours to find that downgrading Color back to version <4 will fix this problem.

That's on you, sorry. Stack traces are almost compulsory for debugging; it's not my fault if your project doesn't output them.
