### ISSUE TITLE
[BUG] `hex` method discards alpha

### ISSUE THREAD

**Issue by devkvlt** [Qix-/color#238]
Fix: `npm uninstall color`

**Comment by Qix-** [comment]
This isn't a bug, it's just part of how the library works. Please search the issues next time.

Duplicate of #72.

**Comment by devkvlt** [comment]
> Please search the issues next time.

Boldly implying I didn't.. 

> This isn't a bug

Discarding user information without even throwing an exception is a massive bug.. It's okay if you don't want to add something like `hexa` and `ahex` in your lib, but at least do us the courtesy of throwing an error when we use `hex` method on a color that has alpha.

**Comment by Qix-** [comment]
No thanks, and the tone isn't appreciated.
