### ISSUE TITLE
Replace max values by modulo for degree

### ISSUE THREAD

**Issue by MoOx** [Qix-/color#24]
(I'm on a PR to add `hwb()` & found a bug that will be fixed by it - capping must be set for the current space prior making the loop for conversion).

0deg == 360deg right ?
So if we tolerate a maximum of 360, we have inconsistent results when converting + capping values. color-convert converts 360 to 0 so we have `hue()` returning 360 or 0 depending on the method we use. If I set hwb using 400, I get 360, but using `hue()` I get 0 cause its using hsl space (that has been converted by color-convert).

Should we stop using max for hue & use a modulo (or nothing). Cause hsl(720deg,..) is valid.
Not sure how to handle that.

Note: for my current PR I'll change max to 359 to be coherent with the "max" approch.

**Comment by Qix-** [comment]
@MoOx did this ever get fixed? Is this basically just `hwb` not modulo-ing hue? We fixed this in `color-convert` for hsl.

**Comment by MoOx** [comment]
Because at the time, the maintainer wasn't open to this breaking change (if my memory is correct). This should be done :)

**Comment by Qix-** [comment]
Agreed. This might be a good thing to stick in `color-convert`, though. Numbers that are outside of the ranges make no sense at the very foundation. If it's fixed there, it'll propagate up and keep the functionality a little more focused in `color`.
