### ISSUE TITLE
Need help to update the @types/color definitions

### ISSUE THREAD

**Issue by Sharcoux** [Qix-/color#240]
I am trying to update the typescript definitions (here)[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/color/index.d.ts] that are quite old. I'd like to add the new `hexa` function from 4.2.0 for instance.

To do so, I need to know what has been added since v3.0. I couldn't find a changelog.

The only thing I know is that there is now a: `hexa` function that returns `#rrggbbaa` result, right? Anything else?

**Comment by Qix-** [comment]
Yeah Github hids this feature pretty well unfortunately. Here's the diff link: https://github.com/Qix-/color/compare/3.0.0..4.2.0

Anyway, yes `.hexa()` appears to be the only change to the API that woul dnee updating :)

**Comment by Sharcoux** [comment]
Perfect, thanks. By the way, if you don't want to use typescript, you might want to consider using JSDoc to benefits from type checking and improve documentation of your lib without transpiling. Check [this](https://gils-blog.tayar.org/posts/jsdoc-typings-all-the-benefits-none-of-the-drawbacks/)

**Comment by Qix-** [comment]
Whenever I get around to figuring out the API going forward (it's been a long standing issue how to effectively and cleanly add features to this library...) I'll probably include typescript definitions directly in the project :)

Thanks for the issue, glad someone is looking at these :)

**Comment by Sharcoux** [comment]
[done](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58522)
