### ISSUE TITLE
Please just add to README about using v3 instead of v4 on unsupported envs

### ISSUE THREAD

**Issue by SrBrahma** [Qix-/color#245]
Please I just lost 4 long and stressful hours today tracking down this issue in my React Native project. It was really awful and couldn't work on what I had to for my contract. I hadn't any info that it was being caused by this lib. The error message I was having didn't give any clue where and what was happening.

I am not asking to change the code, I don't care anymore as I already changed the 4.2.1 to 3.2.1. But be nice to others devs and mention about it on README.

Thanks for the comprehension and feel free to close this after an empathic reflexion.

**Comment by Qix-** [comment]
I have absolutely no idea what you're talking about. This library doesn't use environment variables.

What error are you referring to?

**Comment by SrBrahma** [comment]
By env I mean like React Native environment, not env var.

The enigmatic error I was having was `No identifiers allowed directly after numeric literal`, with no useful stack trace as I was using isLight on start, and when there are errors on RN startup it messes the stack trace. It was pointing to unrelated java files. It's the famous [#222](https://github.com/Qix-/color/issues/222)
