### ISSUE TITLE
Cater for opacity when converting to hex string

### ISSUE THREAD

**Issue by brandon-barker** [Qix-/color#32]
It seems opacity gets ignored when converting a color to hex value.

For example, passing in: `var color = Color("rgba(0, 0, 0, 0.8)");`

and then converting that to a hex value via `color.hexString();` returns `#000000` whereas it actually renders as `#cbcbcb` in the browser?

**Comment by rijkvanzanten** [comment]
With a good part of the major browser now support 4/8-char hex codes, has the time come to start supporting this?

https://caniuse.com/#feat=css-rrggbbaa
