### ISSUE TITLE
Add lab space

### ISSUE THREAD

**Issue by dfcreative** [Qix-/color#42]
There are nice Lab space conversion functions in [color-convert](https://github.com/harthur/color-convert) (`rgb2lab`, `lab2rgb`, etc.). But the Lab space isn’t in color.js.
Maybe it’s worth adding that API to the color? L-channel can be named `'L'` not to interfere with hsl lightness, which is lower-case `'l'`. Same with `'A'` and `'B'`.

What is the reason Lab is excluded from the color? @MoOx  @harthur.

What is possible workaround for that if Lab isn’t going to be included into color?

**Comment by MoOx** [comment]
I am not familiar at all with lab space. 
I think the fact that lab is not in color.js is probably related to the fact that not a lot of people use it.
PR are welcome for this :)

**Comment by Qix-** [comment]
I'll look into this a bit more. I'd like to learn about the Lab space.

One of the reasons right now is that Lab isn't well supported in color-convert (at least, not at the moment).

**Comment by Qix-** [comment]
Lab is much better supported in `color-convert` now. v1 should have all Lab support.
