### ISSUE TITLE
Add schemas

### ISSUE THREAD

**Issue by briancray** [Qix-/color#44]
color-js has schema support (schemaFromDegrees). Are you planning to add this your library? Based on your api it seems trivial to implement.

**Comment by MoOx** [comment]
PR are welcome :)

**Comment by ericdfields** [comment]
+1 gonna take a shot at it.

**Comment by MoOx** [comment]
Please do :)

**Comment by Qix-** [comment]
@briancray schemas for color spaces?

**Comment by briancray** [comment]
I don't have time to write atm, but what I'm thinking would be nice is a new "class" that's an array of color instances, like backbone's Collection is an array of Model instances.

Basically, you would could create an instance using the constructor like, `new Schema([<color or Color instance>, ...])`, or constructor methods such as `Schema.fromDegrees(<color>, <degrees>)` or `Schema.fromCount(<color>, <number of colors>)`

Then you could apply any of the `Color` instance methods to the `Schema` instance, such as `mySchema.lighten(.5)`, which would iterate over the color instances and, if immutable, returns a new schema instance .5 lighter.

**Comment by Qix-** [comment]
Gotcha. I like it; I'll get to work on it.

**Comment by Qix-** [comment]
Not going to make the 1.x makeover but I'm definitely still interested in doing this. 👍

**Comment by Qix-** [comment]
Years later, I feel pretty strongly that this deserves to be its own module somewhere. The general feeling has shifted a bit in terms of dependencies being too "heavy" and thus my viewpoint has changed.

I'd still love to see something like this - it just shouldn't be in this package specifically.

Sorry for the notification years later, and hello to a bunch of past acquaintances. Hope you're all doing well 🙂
