### ISSUE TITLE
'.mix()' method fails to work with cloned color

### ISSUE THREAD

**Issue by ZuBB** [Qix-/color#46]
Hi there!

First of all I would like to excuse for test case that is not as simple as it should be.

I have next code

``` javascript
        ...
        //var baseColor = Color('#73FF73');
        var gtColor = Color('#FF7400');
        var ltColor = Color('#004DFF');
        var colors = { '0.00': 'rgb(255,255,255)' };

        this.getDepDataSet().forEach(function(item) {
            if (typeof colors[item.index] !== 'undefined') {
                return;
            }

            var value = item.number;
            var otherColor = value > 1 ? gtColor : ltColor;
            var weight = (value > 1 ? (value - 1) : (1 - value)) * 3;
            //var resultColor = baseColor.clone().mix(otherColor, weight);
            var resultColor = Color('#73FF73').mix(otherColor, weight);
            colors[item.index] = resultColor.rgbString();
        });
        ...
```

Code above produces a set of colors that are used in table coloring. 
With this code I get a right colors that I am expect (lets call them 'correct'). See 1st pic. When I use code that is commented I get wrong colors (see 2nd pic). In both cases same set of data is used

![2015-01-09-212715_1920x1080_scrot](https://cloud.githubusercontent.com/assets/597016/5685940/a1847ab2-9847-11e4-935f-f46f10e65757.png)

![2015-01-09-213757_1920x1080_scrot](https://cloud.githubusercontent.com/assets/597016/5685979/e90ae722-9847-11e4-8d7a-f84ef9c03590.png)

**Comment by MoOx** [comment]
I'm guessing clone() method is not working properly.

**Comment by ZuBB** [comment]
Just a question of interest: Are you aware if usage of `.clone()` give some performance over `Color()`?

**Comment by MoOx** [comment]
clone() use Color() :)

**Comment by MoOx** [comment]
Btw, that's probably why it's buggy.

**Comment by ZuBB** [comment]
OK, thanks for reply..

**Comment by iamstarkov** [comment]
@ZuBB can you create pull-request with failing tests?

**Comment by ZuBB** [comment]
Hi Vladimir!

I am very busy right now with my own stuff. If this can wait for a couple
of weeks then I will try to do it. Otherwise please assign this to other
person

**Comment by iamstarkov** [comment]
okie

**Comment by iamstarkov** [comment]
@ZuBB please, check 0.9 release. I fixed incorrect implementation

**Comment by MoOx** [comment]
Closing for now, feel free to reopen if you still have issues.

**Comment by ZuBB** [comment]
I made a hacked build (due to other reasons) with new 'mix' method only and things become event worse

![2015-06-22-225226_1920x1080_scrot](https://cloud.githubusercontent.com/assets/597016/8292455/69659428-1938-11e5-9f4b-2f093700ce63.png)

I did small investigation and mix method started to fail case that used to pass. see #61

**Comment by ZuBB** [comment]
@MoOx do you reopen this?

**Comment by Qix-** [comment]
Hi @ZuBB, could you provide a few tests showing the break? If you provide them here I can clean them up and put them in myself.

**Comment by wmira** [comment]
I think the immutability PR fixes this. I used the test below. @ZuBB  please advise if my test case is wrong. The test below fails on previous version.

```javascript
describe('mixing bug is works with immutable', function () {
	it('mix produces proper color with clone or constructor or none cloned', function () {
		var baseColor = Color('#73FF73');
		var gtColor = Color('#FF7400');
		var ltColor = Color('#004DFF');

		[1, 2, 1.3, 1.4, 2.5, 4, 0.7, 8, 1.3].forEach(function (value) {
			var otherColor = value > 1 ? gtColor : ltColor;
			var weight = (value > 1 ? (value - 1) : (1 - value)) * 3;
			var resultColor1 = baseColor.clone().mix(otherColor, weight);
			var resultColor2 = Color('#73FF73').mix(otherColor, weight);
			var resultColor3 = baseColor.mix(otherColor, weight);
			deepEqual(resultColor1, resultColor2);
			deepEqual(resultColor2, resultColor1);
			deepEqual(resultColor1, resultColor3);
			deepEqual(resultColor3, resultColor1);
			deepEqual(resultColor2, resultColor3);
			deepEqual(resultColor3, resultColor2);
		});
	});
});
```

**Comment by ZuBB** [comment]
Hi @wmira!

I do not have a chance to test/run your code but for me it looks it have to cover buggy case.

**Comment by stevemao** [comment]
I'm having trouble with the `mix()` function here
https://github.com/stevemao/color-transitions/blob/master/index.js#L38-L39
```
const color = color1.clone();
color.mix(color2, percent);
```
assume color1 is 'blue' and color2 is 'red', percent is 0.3
I was expecting it's 70% blue and 30% red, but it doesn't look like so.

**Comment by MofeLee** [comment]
Hi @wmira, `baseColor` need call `clone` method~
```js
describe('mixing bug works with immutable', function () {
    it('mix produces proper color with clone or constructor or instance', function () {
        var baseColor = Color('#73FF73');
        var gtColor = Color('#FF7400');
        var ltColor = Color('#004DFF');

        [1, 2, 1.3, 1.4, 2.5, 4, 0.7, 8, 1.3].forEach(function (value) {
            var otherColor = value > 1 ? gtColor : ltColor;
            var weight = (value > 1 ? (value - 1) : (1 - value)) * 3;
            var resultColor1 = baseColor.clone().mix(otherColor, weight);
            var resultColor2 = Color('#73FF73').mix(otherColor, weight);

            var resultColor3 = baseColor.clone().mix(otherColor, weight);
            //                           ^^^^^^ here

            deepEqual(resultColor1, resultColor2);
            deepEqual(resultColor2, resultColor1);
            deepEqual(resultColor1, resultColor3);
            deepEqual(resultColor3, resultColor1);
            deepEqual(resultColor2, resultColor3);
            deepEqual(resultColor3, resultColor2);
        });
    });
});
```

**Comment by Qix-** [comment]
Hey everyone. The cloning problem has been addressed in the rewrite (there is no `.clone()` method anymore - you'll just pass another color). Hopefully this fixes all of these problems. 💃 

Any new issues should be opened as a new bug since it pertains to the rewrite.

**Comment by Qix-** [comment]
Closing this since I believe this is fixed. Please let me know if that's not the case!
