### ISSUE TITLE
Switching spaces change value (rounding ?)

### ISSUE THREAD

**Issue by superguigui** [Qix-/color#57]
``` javascript
var c = Color('#123456');
console.log(c.saturationv(), c.hexString());
// -> 79 #123456

c.saturationv(79);
console.log(c.saturationv(), c.hexString());
// -> 79 #123457

// Should be '79 #123456'
```

[requirebin](http://requirebin.com/?gist=1ca38e176a07a8f73227)

Hi !
I've encountered cases where initializing a color with hexstring and setting its component from another space (hsv) can result in a different hexstring even if the values are set to be the same as before.
I'm guessing the culprit is not in `color` but maybe in `color-convert`? Is there a way to avoid those differences ?

Thanks for this nice library :)

**Comment by MoOx** [comment]
Looks like it's a bug.

**Comment by Qix-** [comment]
A test case for this would be nice in the meantime. If not, I'll make sure this is fixed in v1.

**Comment by Qix-** [comment]
This should be fixed thanks to the `.round()` and `.hex()` methods. Let me know!
