### ISSUE TITLE
Conversion from rgbNumber back to color

### ISSUE THREAD

**Issue by huan086** [Qix-/color#79]
`color.rgbNumber()` returns an integer, however, there is no setter `Color().rgbNumber(int)` that takes this integer to convert back to color.

What's the best way to do a round-trip for rgbNumber?

**Comment by Qix-** [comment]
There really isn't a straightforward way. I'll keep this in mind for when I do the 'makeover' PR for this module. This is something I'd use too.

For the time being this is probably your best bet.

```js
var num = color.rgbNumber();
Color([num >> 16 & 0xFF, num >> 8 & 0xFF, num & 0xFF]);
```

Great question! I'll add this as a feature request.
