### ISSUE TITLE
rgb2hsl bug

### ISSUE THREAD

**Issue by lzl124631x** [Qix-/color#83]
compass will translate rgba(#F1F1F1, .9) into rgba(241, 241, 241, 0.9), and cssnano will compress it into hsla(0,0%,95%,.9).

However, rgb(241, 241, 241) actually equals **hsl(0,0%,94.5%)**. So I think cssnano (Qix-.color) rounded it up, but it will result in UI bug, though minor.

```
var Color = require('Color');
Color('rgba(241,241,241,.9)').hslString()
/// hsla(0, 0%, 95%, 0.9)'
```

[downstream issue: cssnano](https://github.com/ben-eb/cssnano/issues/157#issuecomment-203351365)

**Comment by Qix-** [comment]
Hmm this is tricky. If we use the raw functions that don't round, thrn we might get percentages like `94.5662847765%`, which to me isnt necessarily clean or desired.

@moox / @sindresorhus maybe you will have an idea on the proper way to resolve this.

**Comment by sindresorhus** [comment]
Why wouldn't you want accuracy? I guess you could have a `pretty` option or something.

**Comment by lzl124631x** [comment]
IMHO, the first priority is to make sure the conversion is correct, and then the 2nd is to use the shortest format.

So, as `hsla(0,0%,94.5%,.9)` is shorter than `rgba(241,241,241,.9)`, we should use the former one, rather than `hsla(0,0%,95%,.9)`.

In other cases, if the conversion from rgb to hsl results in long decimals, choose rgb is better.

**Comment by Qix-** [comment]
Hmm. This looks like a bug in [color-string](/qix-/color-string) as well. The fix would be to address the rounding issue there, and begin to use `.raw()` here.

I'm going to set this up for the 1.0 milestone. The re-write will definitely address this.

Thanks for bringing it to my attention. I'll leave this open until it gets fixed.
