### ISSUE TITLE
Was Version 0.12.0 unpublished?

### ISSUE THREAD

**Issue by finnp** [Qix-/color#84]
Hey :)

Just a quick question. This issue https://github.com/greenkeeperio/greenkeeper/issues/156 suggests that  a version `0.12.0` was published (and then unpublished).

Can a contributor confirm that this happened?

Best,
Finn

**Comment by Qix-** [comment]
I don't remember unpublishing anything. O.o that is odd though.

Let me investigate a bit.

**Comment by Qix-** [comment]
@finnp not sure what happened there. I don't think anyone here pushed a release. I don't have any tags or package.json bump commits locally, though it's peculiar that npm is showing that a release was made. It could have been one of the other contributors, but I really hope not.

After chalk/ansi-styles#15 I'm the last person that would be unpublishing anything right now, lol.

Sorry if this mucked anything up.

**Comment by finnp** [comment]
Thank you for checking it out. No worries at all. I am mostly curious about what happened. This is pretty odd. I am really wondering if it was some kind of npm hick-up.

Love this package by the way. Glad to see someone picked up the project.

**Comment by Qix-** [comment]
No problem. I'm willing to accept this was an npm thing.

Going to be releasing a makeover soon (color-string and color-convert have both been made-over). Hope to see more modules using the new versions :+1:
