### ISSUE TITLE
HSL percentage properties should be modify by percent as is

### ISSUE THREAD

**Issue by ivansky** [Qix-/color#91]
Hi everybody,

I have a problem.

For example,

darken(0.15) == sass or less darken(15%)
lighten(0.3) == sass or less lighten(30%)

At the moment we have:

darken(0.15) == current percent - current percent * 0.15
lighten(0.3) == current percent + current percent * 0.3

Why do you multiply percent with another form of percent?

https://github.com/sass/libsass/blob/267df0d59e084363b0da764e0b2126e7e45a92bb/src/functions.cpp#L491
As you can see lighten or darken functions do simple arithmetics.

darken(0.15) == current percent - 15%
lighten(0.3) == current percent + 30%

I think we should unify that functions to prevent misunderstandings.

What do you think about it?

**Comment by Qix-** [comment]
I'm not entirely sure what you're suggesting. Could you show me some examples of what sass does vs what color does?

**Comment by ivansky** [comment]
Lightness is a **percent value**.

## Sass:
For example,

In HSL the black color has 0% lightness and the white has 100%.

![lighten_example1](https://cloud.githubusercontent.com/assets/3938372/16627135/0999c00e-43bd-11e6-8463-f252eb68822d.png)

![1467824232268](https://cloud.githubusercontent.com/assets/3938372/16627134/09975b7a-43bd-11e6-9416-6dcc0cdb9e63.png)

## Less
**Lighten** and **darken** in less: http://lesscss.org/functions/#color-operations-lighten
![1467825519878](https://cloud.githubusercontent.com/assets/3938372/16627654/4044a054-43bf-11e6-9653-fb75283c5a8c.png)

## Color library:
If we look at the behavior of Color library, we will see not expected result:
[Example](https://tonicdev.com/577d3a218833121300d6c328/577d40250f10e21500a1b7a0)
![1467825777524](https://cloud.githubusercontent.com/assets/3938372/16627789/ded55632-43bf-11e6-8ec9-e49a6aaccb85.png)

## Epilogue
So I suggest to do that like in a lot of open source projects.

**Change:**
```
lighten: function (ratio) {
	this.values.hsl[2] += this.values.hsl[2] * ratio;
	this.setValues('hsl', this.values.hsl);
	return this;
}
darken: function (ratio) {
	this.values.hsl[2] -= this.values.hsl[2] * ratio;
	this.setValues('hsl', this.values.hsl);
	return this;
}
```
**To:**
```
lighten: function (ratio) {
	this.values.hsl[2] += ratio * 100%;
	this.setValues('hsl', this.values.hsl);
	return this;
}
darken: function (ratio) {
	this.values.hsl[2] -= ratio * 100%;
	this.setValues('hsl', this.values.hsl);
	return this;
}
```

**Comment by ivansky** [comment]
What do you think about it?

**Comment by Qix-** [comment]
I'll have to look at it. Not entirely sure why youre multiplying by 100%, or what this is solving. I'll investigate a bit further :)

**Comment by ivansky** [comment]
I made the request ;) #92

**Comment by ivansky** [comment]
Let's continue talking about it in pull request #92
