### ISSUE TITLE
Why mix function doesn't work here?

### ISSUE THREAD

**Issue by felixsanz** [Qix-/color#97]
This library is really weird, mutability is causing me so many problems :(

But anyway, why this piece of code:

```javascript
var color = require("color")
const b = color('#fff')
console.log(b.clone().mix(color('black')).hexString())
```

returns `"#000000"` ? it doesn't make any sense. If i remove `clone()` it works.

In fact:

```javascript
console.log(color('#ffffff').clone())
```

```
Color
values: Object
alpha: 1
cmyk: [0, 0, 0, 0]
hsl: [0, 0, 0]
hsv: [0, 0, 0]
hwb: [0, 0, 0]
rgb: [0, 0, 0]
```

**Comment by Qix-** [comment]
Hi there - can you try it with the v1 PR (#96)?

**Comment by felixsanz** [comment]
Doesn't v1 removes .clone() ?

**Comment by Qix-** [comment]
Everything in v1 is immutable. You don't need `.clone()`.

**Comment by felixsanz** [comment]
so what you want me to test exactly?

`console.log(color('#ffffff').clone())`` <- this?

**Comment by Qix-** [comment]
That the `.mix()` function works as you would expect :)

**Comment by felixsanz** [comment]
It does, the problem is `.clone()`. And since the current version needs it... well.... is not usable.

Needs it because if not, i'm mutating colors and that's hard to manage

**Comment by Qix-** [comment]
@felixsanz Good to know - sounds like v1 fixes this :)
