### ISSUE TITLE
mix().string() is giving me invalid rgb strings

### ISSUE THREAD

**Issue by remhume** [Qix-/color#98]
When i call `Color('#eb710c').mix(Color('black'), 0.9).string()` i get `rgb(66.6, 134.1, 175.5)` which is an invalid css property, because of the dots.
I don't think this is the expected result and it returned integers before the 1.x update. But if it is, is there an easy way to get integer rgb values?

**Comment by Qix-** [comment]
Oh strange, could have sworn it allowed for floating point values. The output is expected as per how the library is written but you're right, it's not valid per the spec.

Fix inbound, give me a few minutes. :)

**Comment by Qix-** [comment]
Published as `1.0.2`. I considered this a bugfix since outputs were malformed, and code relying on that broken functionality thus is inherently buggy. Hopefully that doesn't bother anyone.

Thanks for the report!
